# Generated by Django 5.1.7 on 2025-05-13 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChangeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("project", "Project"),
                            ("document", "Document"),
                            ("tag", "Tag"),
                        ],
                        help_text="The entity type to which the action applies",
                        max_length=100,
                    ),
                ),
                (
                    "entity_id",
                    models.IntegerField(
                        help_text="ID of the entity (e.g., user.id, project.id)"
                    ),
                ),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("create", "Created"),
                            ("update", "Updated"),
                            ("delete", "Deleted"),
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("view", "View"),
                            ("action", "Other action"),
                        ],
                        help_text="The type of change or action",
                        max_length=50,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        help_text="Additional contextual data – e.g., IP, device info, payload",
                        null=True,
                    ),
                ),
            ],
        ),
    ]
