# Generated by Django 5.1.7 on 2025-06-01 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChangeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entity_type",
                    models.IntegerField(
                        choices=[
                            (1, "User"),
                            (2, "Project"),
                            (3, "Document"),
                            (4, "Tag"),
                        ],
                        help_text="The entity type to which the action applies",
                    ),
                ),
                (
                    "entity_id",
                    models.IntegerField(
                        help_text="ID of the entity (e.g., user.id, project.id)"
                    ),
                ),
                (
                    "change_type",
                    models.IntegerField(
                        choices=[
                            (1, "Created"),
                            (2, "Updated"),
                            (3, "Deleted"),
                            (4, "Login"),
                            (5, "Logout"),
                            (6, "View"),
                            (7, "Other action"),
                        ],
                        help_text="The type of change or action",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        help_text="Additional contextual data – e.g., IP, device info, payload",
                        null=True,
                    ),
                ),
            ],
        ),
    ]
