# Generated by Django 5.1.7 on 2025-06-05 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "calculations",
            "0003_remove_norm_absorption_min_factor_remove_norm_rt_max_and_more",
        ),
        ("rooms", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="furnishing",
            name="name",
        ),
        migrations.AlterField(
            model_name="furnishing",
            name="material",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="calculations.material"
            ),
        ),
        migrations.AlterField(
            model_name="furnishing",
            name="quantity",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="furnishing",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="furnishings",
                to="rooms.room",
            ),
        ),
        migrations.CreateModel(
            name="RoomSurface",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "area",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Area of material in m²",
                        max_digits=10,
                    ),
                ),
                (
                    "surface_type",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Floor"),
                            (2, "Ceiling"),
                            (3, "Wall A"),
                            (4, "Wall B"),
                            (5, "Wall C"),
                            (6, "Wall D"),
                        ]
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="calculations.material",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="surfaces",
                        to="rooms.room",
                    ),
                ),
            ],
        ),
    ]
