services:
 db:
   image: postgres:17
   environment:
     POSTGRES_DB: postgres
     POSTGRES_USER: postgres
     POSTGRES_PASSWORD: postgres
   ports:
     - "5432:5432"
   volumes:
     - postgres_data:/var/lib/postgresql/data
   healthcheck:
     test: [ "CMD-SHELL", "pg_isready" ]
     interval: 10s
     timeout: 5s
     retries: 5
 backend:
   build:
     context: .
     dockerfile: Dockerfile
   container_name: backend
   ports:
     - "8000:8000"
   depends_on:
     db:
       condition: service_healthy
   volumes:
     - .:/app

volumes:
   postgres_data:



# DB (wstał) -> Backend. -> database ready...