services:
 db:
   image: postgres:17
   environment:
     POSTGRES_DB: postgres
     POSTGRES_USER: postgres
     POSTGRES_PASSWORD: postgres
   ports:
     - "5432:5432"
   volumes:
     - postgres_data:/var/lib/postgresql/data

 backend:
   build:
     context: .
     dockerfile: Dockerfile
   container_name: backend
   ports:
     - "8000:8000"
   depends_on:
     - db
   volumes:
     - .:/app

volumes:
   postgres_data: