# Generated by Django 5.1.7 on 2025-05-25 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                ("freq_120", models.DecimalField(decimal_places=2, max_digits=22)),
                ("_250", models.DecimalField(decimal_places=2, max_digits=22)),
                ("_500", models.DecimalField(decimal_places=2, max_digits=22)),
                ("_1000", models.DecimalField(decimal_places=2, max_digits=22)),
                ("_2000", models.DecimalField(decimal_places=2, max_digits=22)),
                ("_4000", models.DecimalField(decimal_places=2, max_digits=22)),
            ],
        ),
        migrations.CreateModel(
            name="Norm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "application_type",
                    models.CharField(
                        choices=[
                            ("1", "Height-dependent"),
                            ("2", "No dependency"),
                            ("3", "Volume-dependent"),
                            ("4", "Speech Transmission Index"),
                        ],
                        default="2",
                        max_length=2,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Calculation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reverberation_time",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("is_within_norm", models.BooleanField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "room_height",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "room_volume",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "sti",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                (
                    "norm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="calculations.norm",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NormAbsorptionMultiplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("multiplier", models.DecimalField(decimal_places=2, max_digits=22)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("1", "Height-dependent"),
                            ("2", "Volume-dependent"),
                            ("3", "Speech Transmission Index"),
                            ("4", "No dependency"),
                        ],
                        max_length=10,
                    ),
                ),
                ("height_min", models.FloatField(blank=True, null=True)),
                ("height_max", models.FloatField(blank=True, null=True)),
                ("volume_min", models.FloatField(blank=True, null=True)),
                ("volume_max", models.FloatField(blank=True, null=True)),
                ("sti_min", models.FloatField(blank=True, null=True)),
                ("sti_max", models.FloatField(blank=True, null=True)),
                (
                    "norm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="calculations.norm",
                    ),
                ),
            ],
        ),
    ]
