# Generated by Django 5.1.7 on 2025-04-29 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                ("freq_120", models.DecimalField(decimal_places=2, max_digits=22)),
                ("_250", models.DecimalField(decimal_places=2, max_digits=22)),
                ("_500", models.DecimalField(decimal_places=2, max_digits=22)),
                ("_1000", models.DecimalField(decimal_places=2, max_digits=22)),
                ("_2000", models.DecimalField(decimal_places=2, max_digits=22)),
                ("_4000", models.DecimalField(decimal_places=2, max_digits=22)),
            ],
        ),
        migrations.CreateModel(
            name="Norm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Calculation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reverberation_time",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("is_within_norm", models.BooleanField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "norm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="calculations.norm",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NormAbsorptionMultiplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "absorption_multiplier",
                    models.DecimalField(decimal_places=2, max_digits=22),
                ),
                (
                    "norm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="calculations.norm",
                    ),
                ),
            ],
        ),
    ]
