# Generated by Django 5.1.7 on 2025-06-05 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NormRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "volume_min",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Minimum room volume in m³ (optional)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "volume_max",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum room volume in m³ (optional)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "height_min",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Minimum room height in meters (optional)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "height_max",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum room height in meters (optional)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "rt_max",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum reverberation time T in seconds (optional)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "sti_min",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Minimum speech transmission index STI (optional)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "absorption_min_factor",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Minimum required sound absorption factor (optional, e.g. 0.6 × S)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "norm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requirements",
                        to="calculations.norm",
                    ),
                ),
            ],
        ),
    ]
