# Generated by Django 5.1.7 on 2025-06-05 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("calculations", "0002_normrequirement"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="norm",
            name="absorption_min_factor",
        ),
        migrations.RemoveField(
            model_name="norm",
            name="rt_max",
        ),
        migrations.RemoveField(
            model_name="norm",
            name="sti_min",
        ),
    ]
