# Generated by Django 5.1.7 on 2025-05-25 16:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProjectChangeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "change_type",
                    models.IntegerField(
                        choices=[
                            (1, "Created"),
                            (2, "Deleted"),
                            (3, "Shared"),
                            (4, "Downloaded"),
                            (5, "Edited Dimensions"),
                            (6, "Edited Furnishing"),
                            (7, "Edited Standard"),
                        ]
                    ),
                ),
                ("change_description", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name": "Project Change Log",
                "verbose_name_plural": "Project Change Logs",
                "ordering": ["-timestamp"],
            },
        ),
    ]
