# Generated by Django 5.1.7 on 2025-04-29 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChangeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("user", "Użytkownik"),
                            ("project", "Projekt"),
                            ("document", "Dokument"),
                            ("tag", "Tag"),
                        ],
                        help_text="Typ obiektu, którego dotyczy akcja",
                        max_length=100,
                    ),
                ),
                (
                    "entity_id",
                    models.IntegerField(
                        help_text="ID obiektu (np. user.id, project.id)"
                    ),
                ),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("create", "Utworzono"),
                            ("update", "Zmieniono"),
                            ("delete", "Usunięto"),
                            ("login", "Logowanie"),
                            ("logout", "Wylogowanie"),
                            ("view", "Podgląd"),
                            ("action", "Inna akcja"),
                        ],
                        help_text="Typ zmiany lub akcji",
                        max_length=50,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        help_text="Dodatkowe dane kontekstowe – np. IP, device info, payload",
                        null=True,
                    ),
                ),
            ],
        ),
    ]
