# Generated by Django 5.1.7 on 2025-06-04 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0002_initial"),
        ("plans", "0003_create_default_plans"),
    ]

    operations = []
